spring:
  datasource:
    data: classpath:data.sql
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    schema: classpath:schema.sql
    url: jdbc:h2:file:D:/Lakshmi/test
  jpa:
    properties:
      hibernate:
        generate_statistics: 'false'
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: 'true'
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
